config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  root "posts#index"
  
  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
  validates :name, presence: true
  validates :body, presence: true, length: { minimum: 5 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    
    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @posts = Post.all.order('created_at DESC')
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  
  def show
    @post = Post.find(params[:id])
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to root_path
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	<% if user_signed_in? %>
		<p><%= link_to 'Delete', [comment.post, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %>
		</p>
 	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<br>
	<p>
		<%= f.submit %>
	</p>
	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
			
			
<head>
	<link rel="icon" type="image/svg" href="logo.svg">
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<img src="/assets/Rafael-Nadal-logo.png" height="50" width="50" ></img>
			<% end %>
		</div>

		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="https://twitter.com/DanielLdy2009">Twitter</a></li>
			<li><a href="https://instagram.com/piryun/">Instagram</a></li>
			<li><a href="https://www.facebook.com/profile.php?id=100002950709271">Facebook</a></li>
			<li><a href="mailto:ldy2009@hotmail">Email</a></li>
		</ul>

		<% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
		<% end %>
	</div>

	
	<div id="header">
			
		<div class="home_button">
			<button class="button"><%= link_to "Home", root_path %></button>
		</div>
		
		<div class="music_control">
			<% if user_signed_in? %>
				<audio src="/灌篮高手 - 捕捉闪耀的瞬间.mp3"  type="audio/mp3" controls preload="auto" volume="0.75">
					Your browser does not support HTML audio tag!
				</audio>
			<% end %>
		</div>
			
		<div class="buttons">
			<% if user_signed_in? %>
				<button class="button"><%= link_to "New Post", new_post_path %></button>
				<button class="button"><%= link_to "Log out", destroy_user_session_path, :method => :delete %></button>
			<% else %>
				<button class="button"><%= link_to "Sign Up", new_user_registration_path %></button>
				<button class="button"><%= link_to "Log In", new_user_session_path %></button>
			<% end %>
		</div>
	</div>
	<div id="main_content">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<div id="about_page">
	<div>
		<h1>Voyage<h1>
	</div>
	
	<div class="BlogImageCenter">
		<img src="/assets/IMG_0551.jpg" class="img－show" alt="cunli.jpg" width="460" height="600">
		<br/>
		<br/>
		<img src="/assets/IMG_0560.jpg" class="img－show" alt="niagara.jpg" width="700" height="460">
	</div>
	
</div>

app/views/posts/_form.html.erb
	<%= form_for @post do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<p>
			<%= f.label :title %><br />
			<%= f.text_field :title %>
		</p>
	
		<p>
			<%= f.label :content %><br />
			<%= f.text_area :body %>	
		</p>
	
		<p>
			<%= f.submit %>
		</p>
	<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
	<button class= "button", id="edit_button">
		<%= link_to "Back", post_path(@post) %>
	</botton>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class = "post_wrapper" >
		<h2 class = "title"><%= link_to post.title, post %></h2>
		<p class = "date" ><%= post.created_at.strftime("%B, %d, %y") %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= form_for :post, url: posts_path do |f| %>
		<%= if @post.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
		<p>
			<%= f.label :title %><br />
			<%= f.text_field :title %>
		</p>
	
		<p>
			<%= f.label :body %><br />
			<%= f.text_area :body %>	
		</p>
	
		<p>
			<%= f.submit %>
		</p>
	<% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class = "title" >
		<%= @post.title %>
	
	</h1>
	<p class = "date" >
		<%= time_ago_in_words(@post.created_at) %> Ago
		
	</p>

	<p class = "body">
		<%= @post.body %>
	</p>
	
	<% if user_signed_in? %>
		<div class = "buttons">
			<button class = "editpost_button"><%= link_to 'Edit', edit_post_path(@post) %></button>
			<button class = "deletepost_button"><%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %></button>
		</div>
	<% end %>
</div>
	
<br/>
<br/>
<div id="comments">
	<h2>All Comments(
		<%= @post.comments.count %> 
		)
	</h2>
	<%= render @post.comments %>
		
	<h3>Add a comment</h3>
	<%= render "comments/form" %>
</div>